title: Failure Infrastructures
tagline:
description: Failure Infrastructures
banner: /img/tonermap.png
#favicon: <favicon url>
#logo: <logo url>

# When using a custom domain these fields must be updated to match
# the Github account and repository name
#acct: <GitHub account/username>
#repo: <GitHub repository>

######################################################
# Defines options shown in the header navigation menu
######################################################
nav:
- label: Contact 
  icon: fas fa-envelope
  action: contact-us


# If a contact-us action is defined for the nav menu a contact form will be enabled
# The following information is used in the display and processing of the contact form.
contactForm:
  to:
  - JSTOR Labs <dpapadop@risd.edu>
  subject: Collapse